{% set name = "napari-toothfairy-annotator" %}
{% set version = "0.0.18" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 9e3c222be3cede1ab87e32c2e707617bf45d5b7c4158a1ea4c9911f2b663dfb2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - numpy
    - magicgui
    - qtpy
    - scikit-image
    - napari >=0.4.18

test:
  imports:
    - napari_toothfairy_annotator
  commands:
    - pip check
  requires:
    - pip
    - pyqt

about:
  home: https://github.com/LucaLumetti/napari-toothfairy-annotator
  summary: The plugin employed to annotate volumes employed in the ToothFairy 2 Challenge
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - LucaLumetti
